site_name: Planimation
nav:
    - Home: README.md
    - Deployment: Deployment_guide.md
    - VFG: VFG_guide.md
    - Visualiser: Visualiser_guide.md
    - Animation Profile: ap_guide.md
    - User Guide: ug1.md
theme: readthedocs