site_name: Planimation
nav:
    - User Information:
        - Home: README.md
        - User Guide: ug1.md
    - Developer Information:
        - Deployment: Deployment_guide.md
        - VFG: VFG_guide.md
        - Visualiser: Visualiser_guide.md
        - Animation Profile: ap_guide.md


theme: readthedocs